"""Added a
ge column

Revision ID: a02049622006
Revises: bc9bcff3e8ef
Create Date: 2025-03-28 23:45:25.494106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02049622006'
down_revision = 'bc9bcff3e8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(), nullable=False, server_default='0 years 0 months'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
